scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

    email:
        enabled: true
        sender_email: "contact@dev-services.ovh"